### ISSUE TITLE
Log object's props are mutated

### ISSUE THREAD

**Issue by cilindrox** [continuationlabs/white-out#3]
I've set up a project using `good`, `good-console` and `white-out` as detailed [here][1].

Configuration is set to `censor` fields:

```json
"module": "white-out",
"args": [{
    "password": "censor"
}]
```

The following happens when calling `request.server.log` on my handler:

```js
const data = { password: 'itsasecret' };
request.server.log(['info', 'tag'], `data: ${data}`);

// 'data.password' has now been modified/replaced with 'X's :

// prints "password: 'XXXXXXXXXX'"
console.log(data);
```

Shouldn't white-out be making a copy of the object instead of mutating it?

[1]: https://github.com/cilindrox/good-censor

**Comment by arb** [comment]
No. Each reporter pipelines gets it's own copy of the object so transform streams are free to make changes as they see fit without worrying about impacting other reporting streams. 

Also, making a deep copy every time `_transform` is called would get extremely expensive since it's called for every object that goes through the pipeline.

**Comment by cilindrox** [comment]
Then the expecting behavior of using the `censor` prop is to have the data passed to the logger being modified?

**Comment by arb** [comment]
Yes this working as intended. If you've used the `censor` option in previous versions of good, it did it the same way. This just makes it it's own module. 

If you *really* want to make a copy before changing, you could add a clone transform stream in your pipeline before white-out. I wouldn't recommend that, but that's one way to achieve what you're describing.

**Comment by cilindrox** [comment]
Awesome, appreciate the detailed explanation @arb
